version: '3.7'
services:
  app:
    image: app
    build: .
    ports:
      - target: 5000
        published: 80
    depends_on:
      - mysql
    environment:
    - DB_ENTRY=${DB_ENTRY}
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=flask_database
